name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # paper:
  #   runs-on: ubuntu-latest
  #   name: Paper Draft
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
      
  #     # This step builds a draft PDF of the paper using the Open Journals draft action.
  #     - name: Build draft PDF
  #       uses: openjournals/openjournals-draft-action@master
  #       with:
  #         journal: joss  # Specifies the journal format (e.g., JOSS).
  #         # Path to the paper markdown file within the repository.
  #         paper-path: paper/paper.md

  #     # This step uploads the generated PDF as an artifact for later access.
  #     - name: Upload
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: paper  # Artifact name.
  #         # Path to the generated paper PDF file.
  #         path: paper/paper.pdf
          
  formatting:
    # needs: paper  # Removed dependency on the paper job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Setup black environment
        run: |
          pip install --upgrade pip
          pip install black

      - name: Check formatting with black
        run: |
          black --check spafe

  testing:
    needs: formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup testing environment
        run: |
          pip install --upgrade pip
          pip install .[tests]

      - name: Test
        run: |
          pytest -x --cache-clear -n 8 -q --cov=./ || --force-yes
          codecov
